require 'optparse'
require 'tempfile'
require 'uri'
require 'nokogiri'

require_relative 'core/version'
require_relative 'core/argv_splitter'
require_relative 'core/opt_parser'
require_relative 'core/resource_switcher'
require_relative 'core/error_layer'
